CREATE TABLE IF NOT EXISTS energy_records (
    id INT PRIMARY KEY AUTO_INCREMENT,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `usage` FLOAT NOT NULL,
    device VARCHAR(100) NOT NULL,
    duration FLOAT DEFAULT 1
);