CREATE TABLE IF NOT EXISTS energy_records (
    id SERIAL PRIMARY KEY,
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    usage FLOAT NOT NULL,
    device VARCHAR(100) NOT NULL
);

ALTER TABLE energy_records ADD COLUMN IF NOT EXISTS duration REAL DEFAULT 1;